### ISSUE TITLE
[RFC] Lumen / Laravel 7 Compatiblity

### ISSUE THREAD

**Issue by th0rn0** [xedi/laravel-behat#189]
Title.

Had a look but I dont think we can get it compatible with 7.

 xedi/laravel-behat 2.0.0 requires symfony/config ^4 

However

symfony/config 4.0.x-dev conflicts with symfony/http-kernel[5.0.x-dev]

v5 of Symfony is Laravel/Lumen 7. Any thoughts on this? had a quick look but not sure. Alias perhaps?

**Comment by Smudge3806** [comment]
Can we upgrade `symfony/config` to something that won't conflict with `symfony/http-kernel[5.0.x-dev]`?

**Comment by Smudge3806** [comment]
> Can we upgrade `symfony/config` to something that won't conflict with `symfony/http-kernel[5.0.x-dev]`?

I can double check want parts of `config` the library requires and see if they work in `5.x`

**Comment by th0rn0** [comment]
yea please,

From what I can see its not compatible with v7 as it needs those updated sympony components that are not supported by behat.

**Comment by Smudge3806** [comment]
Fixed in https://github.com/xedi/laravel-behat/releases/tag/3.0.0
